export const CHART_CONFIG = {
  HEIGHT_MOBILE: 200,
  HEIGHT_DESKTOP: 300,
  TICK_FONT_SIZE: 12,
  MIN_TICK_GAP: 50,
  Y_AXIS_WIDTH: 45,
  THOUSAND_THRESHOLD: 1000,
  ANIMATION_DURATION_MS: 1500,
  DOT_RADIUS: 4,
  ACTIVE_DOT_RADIUS: 6,
} as const
